### ISSUE TITLE
Subtitle auto generated

### ISSUE THREAD

**Issue by Flop-0ut** [anxdpanic/plugin.video.youtube#247] opened 2021-11-14 04:49 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version:6.8.18+matrix.1
* Kodi Version:19.3
* Kodi GUI Language:German
* Operating System: Ubuntu 20.04
* Operating System Language:German

------

### Expected Behavior

Please describe the behavior you are expecting.

German subtitles for videos in other languages
------

### Current Behavior

Only 

What is the current behavior?

I can choose German subtitles in the addon settings, but it no longer works since 6.8.18.alpha2 + matrix.1

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by johanbetterman** [comment] 2021-11-14 12:01
Yes, I can confirm, no auto generated subtitles in list since  6.8.18.alpha2 + matrix.1
Now running 6.8.18 + matrix.1 without subs

When I downgrade to  6.8.18.alpha2 + matrix.1 I get the full list of subtitles back

Thought I was the only one using this functionality

**Comment by kedarz** [comment] 2021-11-17 06:23
I can confirm too this issue

**Comment by 03stevensmi** [comment] 2022-03-18 17:02
ok seriously, this is ridiculous! I am (or... Was) using this feature too! In fact... It was literally one of the main reasons I started using this amazing plugin! I have not even touched this addon since around the 8th of novembre 2021 Because of this EXACT issue with subtitle translation! I decided to give up on this addon for the near future! It is now the middle of MARCH 2022 and i just found out that the subtitles were fixed only a month later after i gave up! So i installed both the latest release & the master branch and found a lazy attempt fix. Yeah, the original launguage works... you fixed THAT but left out auto translation and the other subtitle problems!! You even put it in the wizard where i set my language to english and have the captions set to English automatically... But they just don't bother showing or downloading. Its been almost 5 MONTHS!

**Comment by 03stevensmi** [comment] 2022-03-18 17:06
Please can you fix this feature instead of ignoring it all together!! And please don't say it hadn't been ignored, its on the todo list etc etc, its been under 5 months! It HAS been ignored along with other important main features such as youtube recommendation etc. Thank You!

**Closed as completed** 2024-02-23 17:03 UTC
Labels: bug
