### ISSUE TITLE
This video isn't available on this app 

### ISSUE THREAD

**Issue by f2hamza** [anxdpanic/plugin.video.youtube#443] opened 2023-04-15 00:11 UTC
It says this video isn't available on this app
im on latest version btw

**Comment by FunctionalHacker** [comment] 2023-04-15 10:59
I get the same on this video https://www.youtube.com/watch?v=OegJ6nX57KY

Most videos seem to work though

**Comment by MatthiasCoppens** [comment] 2023-04-16 10:48
Duplicate of #442

**Comment by FunctionalHacker** [comment] 2023-04-16 10:58
Yes, let's close this in favor of #442

**Closed as completed** 2023-04-16 12:02 UTC
