### ISSUE TITLE
Behavior with removing items in v7.0.3 Beta 2

### ISSUE THREAD

**Issue by Mo1967** [anxdpanic/plugin.video.youtube#571] opened 2024-02-01 11:20 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3 Beta 2
* Kodi Version: Nexus 20.3
* Kodi GUI Language: Default
* Operating System: Android
* Operating System Language: Default

------

### Expected Behavior

When remove in the addon an item from playlist working synchron in both directions (addon and YT-website),

------

### Current Behavior

Remove of an item don't work in the addon, but works fine in the other way from website to addon. 

------

### Log and screen-recording from addon and YT-website

https://paste.kodi.tv/ewuqacegon.kodi

https://youtu.be/vkcNPliN3-U

------

### Additional Information

- Reference to #558 
- In latest v7.0.2.2  they are not this behavior.
- Tomorrow my wife will testing v7.0.3 Beta 2

------

Thank you very much and have you a great day!

**Comment by MoojMidge** [comment] 2024-02-01 22:03
Duplicate of #570

**Closed as completed by MoojMidge** 2024-02-01 22:03 UTC
Labels: bug
