### ISSUE TITLE
Kodi 21.0 Alpha 1 Ubuntu 22.04 LTS Addon throwing error

### ISSUE THREAD

**Issue by mralapete** [anxdpanic/plugin.video.youtube#745] opened 2024-05-03 17:20 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: plugin.video.youtube-7.0.6.3+unofficial
* Kodi Version:21.0 Alpha 1
* Kodi GUI Language:
* Operating System: Ubuntu 22.04 lts
* Operating System Language: English

------

### Expected Behavior

Please describe the behavior you are expecting.

Youtube addon to launch

------

### Current Behavior

What is the current behavior?
Youtube addon throwing error and will not launch

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Installed addon
2. Launched from GUI
3. 

------

### Log

CAddonMgr::FindAddon: plugin.video.youtube v7.0.6.3+unofficial.1 installed
2024-05-03 17:47:29.442 T:4662    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'InvalidJSONError' from 'requests.exceptions' (/usr/lib/python3/dist-packages/requests/exceptions.py)
                                                   Traceback (most recent call last):
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/service.py", line 13, in <module>
                                                       from youtube_plugin.kodion import service_runner
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/service_runner.py", line 15, in <module>
                                                       from .monitors import PlayerMonitor, ServiceMonitor
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/__init__.py", line 14, in <module>
                                                       from .service_monitor import ServiceMonitor
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/service_monitor.py", line 18, in <module>
                                                       from ..network import get_connect_address, get_http_server, httpd_status
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/__init__.py", line 12, in <module>
                                                       from .http_server import (
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 19, in <module>
                                                       from .requests import BaseRequestsClass
                                                     File "/home/peter/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 17, in <module>
                                                       from requests.exceptions import InvalidJSONError, RequestException
                                                   ImportError: cannot import name 'InvalidJSONError' from 'requests.exceptions' (/usr/lib/python3/dist-packages/requests/exceptions.py)
                                                   -->End of Python script error report<--

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment] 2024-05-03 21:29
Duplicate of https://github.com/anxdpanic/plugin.video.youtube/issues/610

**Closed as not planned by MoojMidge** 2024-05-03 21:29 UTC
Labels: bug

**Comment by mralapete** [comment] 2024-05-04 00:11
I’m not sure if you are aware that the Team Kodi PPA maintainer walked away recently so anyone using Ubuntu 22.04 LTS or any other distro that depend on updates are stuck with Kodi 21.0 Alpha 1 unless they compile Kodi or use the Flathub version. Bit of a mess really. My Ubuntu 22.04 LTS has the latest version of requests as per sources so that could not be the issue.

**Comment by MoojMidge** [comment] 2024-05-04 00:33
> My Ubuntu 22.04 LTS has the latest version of requests as per sources so that could not be the issue.

No it doesn't. If it did, then you wouldn't get that error. You are using a version of requests that is at least 2 years old.

**Comment by mralapete** [comment] 2024-05-04 01:30
You do understand I’m using Ubuntu 22.04 LTS Jammy Jellyfish. I am served the latest updates that are available in sources and believe me I have updated to the latest version of requests. What version of Python and Python-requests does your addon demand so I can investigate this issue further.

**Comment by MoojMidge** [comment] 2024-05-04 05:57
One of us is undoubtedly confused, but if you think it is me, then I'm not sure why you are seeking help here.

You are using a 2+ year out-of-date version of requests because that is what your distribution offers. The required version is linked in the issue i have already pointed you to. 

There are easy, easy but trouble prone, not so easy, and difficult options available to you. Regardless, this is not a general support forum and it is a users responsibility to keep their system updated, not this plugin.

**Comment by mralapete** [comment] 2024-05-06 19:03
I wasn’t looking for general support. Just trying to determine what route to take to resolve the problem.

As it happens I uninstalled the Kodi 21 Alpha RC1 version, changed the sources in the Jammy Jellyfish repo from nightly to stable which brought me back to Kodi 20 stable. I reinstalled your add on and everything working normally now. 

Unfortunately with the demise of the Team Kodi PPA it won’t be as straightforward to install Kodi as it was In Ubuntu previously. While compiling Kodi is probably the most efficient option I don’t see too many Kodi users choosing that option and Kodi Flatpak is not exactly the smoothest experience I’ve ever had.

**Comment by MoojMidge** [comment] 2024-05-06 21:29
> Just trying to determine what route to take to resolve the problem.

The easy option I was referring to was to use the older stable release or the Kodi Flatpak package, rather than using a 1 year old Alpha 1 release of Kodi in a now superceded LTS edition of your chosen distribution.

The entire problem only occurs because of a bunch of user choices that probably shouldn't be made, and which the plugin cannot cater for.

Downgrading Kodi, updating via Flatpak, updating your OS, force updating the system requests package, or compiling Kodi yourself all would have worked, but really has nothing to do with this plugin.

Anyway, glad you got it sorted and took the time to identify what you ended up doing, which might help others in this somewhat unusual situation.

> Kodi Flatpak is not exactly the smoothest experience I’ve ever had.

Never tried it myself, but what is the problem with it?

**Comment by mralapete** [comment] 2024-05-06 22:06
Flatpak Kodi is sluggish. You can feel the performance difference plus a load of unwanted dependencies are installed which doesn’t help either. 

I’m over 20 years using Ubuntu, particularly LTS versions purely for stability purposes but myself and Ubuntu will soon be parting company. It’s not the distro it once was. Kodi seems to be following a similar trajectory too. 

They do say some things are too big to fail but look what happened to MythTV, the go to media centre application for Linux back in the day.

**Comment by MoojMidge** [comment] 2024-05-07 17:08
Fair enough, will have to keep that in mind before suggesting people use it.
