### ISSUE TITLE
Comments problem

### ISSUE THREAD

**Issue by drrak** [anxdpanic/plugin.video.youtube#878] opened 2024-08-14 09:04 UTC
_Transtaltor:_

Comments work in My Subscriptions, but when I try to check comments in Recommendations, something breaks and they don't work anywhere. There's something about API, but my key is still the same and I haven't changed anything there.

_RPi 4,, LibreELEC 12.0.0, YouTube 7.0.9_

**Comment by MoojMidge** [comment] 2024-08-22 22:19
Will be fixed in next release. In the meantime you can update manually from this test version to confirm that the problem is resolved:
https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip

**Closed as completed** 2024-08-24 21:42 UTC
Labels: bug
