### ISSUE TITLE
No videos appearing when searching or clicking "Popular Now"

### ISSUE THREAD

**Issue by scomo420** [anxdpanic/plugin.video.youtube#611] opened 2024-03-02 05:28 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.4.0
* Kodi GUI Language: English
* Operating System: Windows 10
* Operating System Language: English

------

### Expected Behavior

Videos appearing in search results and popular now

------

### Current Behavior

No videos appear in search results, just the categories "Channels", "Playlists", and "Live", clicking any of these categories also shows no videos.
This bug happens on my android tablet, raspberry pi with Libreelec, and Windows 10 PC however, occasionally the videos will show and play fine.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Install the YouTube addon
2.  Make a search or click Popular Now
3.  No videos will appear in the search results

------

### Log

There is no log created from this bug

------

### Additional Information

Occasionally, the videos will appear and play fine, but most of the time they won't

I have tried:

- Re-installing the addon
- Re-installing Kodi
- Adding my own API keys
- Testing on different devices

------
Clicking "Popular Now"
![2](https://github.com/anxdpanic/plugin.video.youtube/assets/161916158/c47538c8-1b10-464d-8480-8197feee7f51)
Searching for a video
![Capture](https://github.com/anxdpanic/plugin.video.youtube/assets/161916158/08047067-40aa-46bd-baa2-235b898606ae)

**Comment by MoojMidge** [comment] 2024-03-02 09:25
Duplicate of #585

Also #587 and #591...

**Closed as completed by MoojMidge** 2024-03-02 09:25 UTC
Labels: bug
