### ISSUE TITLE
Some links shared to the plugin fail to play, stuck at busy spinner, no error cause in log

### ISSUE THREAD

**Issue by jmbreuer** [anxdpanic/plugin.video.youtube#250] opened 2021-11-23 19:16 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 6.8.18+matrix.1
* Kodi Version: 19.1
* Kodi GUI Language: EN
* Operating System: LibreELEC 10.0.0
* Operating System Language: EN

------

### Expected Behavior

Any links shared for playback via the `plugin://plugin.video.youtube/uri2addon/` path/endpoint should either play, or an error message (preferably, detailing the reason) should be shown within a reasonable amount of time, 10-30 seconds.

------

### Current Behavior

Sharing some (in principle valid) YouTube links causes the busy spinner to be displayed for many minutes. One time I was shown a nondescript error message (item failed to play, check log); on reproduction the spinner is going for more than 12 minutes now. When I press 'Back', the "item(s) failed to play" message is shown.

There is no information either shown in UI or in the logs that would detail what's going wrong.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Share https://m.youtube.com/watch?v=BeT_reBoruI&list=UU8aSR_qI6MCIJkGJfPn1RvQ&index=4 for playback, using Yatse on an Android device or Chorus / The Lab, `Player.Open`, params:`{"item": {"file": "plugin://plugin.video.youtube/uri2addon/?uri=https%3A%2F%2Fm.youtube.com%2Fwatch%3Fv%3DBeT_reBoruI%26list%3DUU8aSR_qI6MCIJkGJfPn1RvQ%26index%3D4"}}`
2. Watch spinner

------

### Log

Isolated log of reproduced error: https://paste.kodi.tv/efocavexad.kodi

Live log of first occurence: https://paste.kodi.tv/jogajuvori.kodi
(this one is much less readable, as I was queuing the video in question while another one was playing)

------

### Additional Information

Processing this request takes a wrong turn somewhere on the `uri2addon` side of things; playing the same video with plain `plugin://plugin.video.youtube/play/?video_id=BeT_reBoruI` works as expected.

------

**Comment by shankarinece** [comment] 2021-11-24 05:22
This issue is seen in Kodi, running on OSMC. Youtube plugin v6.8.18+matrix.1, Kodi v19.1 running on RPi3 and on RPi4. 
This ticket is possibly a duplicate of https://github.com/anxdpanic/plugin.video.youtube/issues/248

**Comment by jmbreuer** [comment] 2021-11-24 12:46
I'd like to clarify (concerning the possible duplicate): I only see this type of link not working, I have a hunch it has to do with a `list`/`index` parameters in the URI.

I do not experience any of the other symptoms mentioned in #248. I can navigate the menus fine and also share by (only) `video_id` for playback, I'm not aware of any other stuck busy loops. The "My Subscriptions" menu item takes a while to load, but that's nothing new - it became slow for me after it was switched from API to RSS quite a while back, from what I understand.

Yesterday, after reproducing this issue, I saw that LibreELEC 10.0.1 was out and upgraded, no change at all for me. I'm on x86_64-Generic; a dedicated i5-based HTPC.

**Closed as completed** 2023-12-26 00:56 UTC
Labels: bug
