### ISSUE TITLE
You Tube  kodi. 

### ISSUE THREAD

**Issue by Greg0580** [anxdpanic/plugin.video.youtube#323] opened 2022-08-27 18:48 UTC
I have  Tried to play some videos and it comes up that the player ineeds to be updated to play.  And when you try to play Some  Movie, TV show,  etc.  It comes up saying it might be  can't play course of age restrictions.  And when you turn off Age gate and change to non age restrictions on search it still won't play some videos 
Regards 
Greg.

**Comment by FunctionalHacker** [comment] 2022-09-27 14:11
Duplicate of  #278. Please close this one.

Also next time, please try to title your issues with something that is actually related to the issue. And this one is a bug, not an enhancement.

**Closed as completed** 2024-04-02 00:59 UTC
Labels: enhancement
