### ISSUE TITLE
Viewed video on Youtube addon not synced with Youtube account

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#581] opened 2024-02-17 14:36 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.3.beta.3
* Kodi Version: 20.3
* Kodi GUI Language: French
* Operating System: Android
* Operating System Language: French

------

### Expected Behavior

Within Youtube addon 7.0.1, when i watched video, history playback was synced with Youtube account. I skipped Youtube 7.0.2.2 because of subtitles bug. 

------

### Current Behavior

With latest Youtube addon 7.0.3.beta.3, watched video is not synced anymore with Youtube account. 

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Youtube 7.0.3.beta.3
2. Click on play
3. History playback doesn't sync with watched video on Youtube account.

**Comment by MoojMidge** [comment] 2024-02-17 18:34
Nothing can be done without a debug log

**Comment by victore447** [comment] 2024-02-17 19:11
🖐️![18](https://github.com/anxdpanic/plugin.video.youtube/assets/48101775/201d0341-2453-4914-b209-567a482e0644)
**_Dead beta version._**
☝️On the official version 7.0.2.2 access has been refused for a few hours now.
Even after updating the IDs in the Google console.
☝️On browser via kodi/youtube url or in the addon in kodi etc... 
your three methods no longer allow access to the personal YouTube account✔️
![Acces](https://github.com/anxdpanic/plugin.video.youtube/assets/48101775/78282e22-10ff-4125-8571-d47052e6cad2)

**Comment by MoojMidge** [comment] 2024-02-17 22:14
@victore447 - What does that have to do with this issue?

Please try to search before creating new issues or responding to unrelated issues.

You haven't set up your OAuth access correctly. See #204

**Comment by karlo2105** [comment] 2024-02-17 22:36
@MoojMidge
In settings -> advanced -> update playback history on Youtube: i ticked on. 
It shows viewed video only, but history playback isn't synced with Youtube account. Below, you can find debug for Youtube addon. 

2024-02-17 23:25:17.336 T:9084     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.3) on Nexus (Kodi-20.3) with Python 3.11.2
                                                   Path: /special/new_uploaded_videos_tv/
                                                   Params: {'category_label': 'Mes abonnements'}
2024-02-17 23:25:20.959 T:12018   error <general>: [plugin.video.youtube] Request failed
                                                   Status: 404 - Not Found
                                                   Stack trace (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 995, in _bootstrap
                                                       self._bootstrap_inner()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
                                                       self.run()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/threading.py", line 975, in run
                                                       self._target(*self._args, **self._kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 1502, in fetch_xml
                                                       _response = self.request(_url, headers=headers)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 118, in request
                                                       stack_trace = format_stack()
                                                   
2024-02-17 23:25:22.695 T:9084     info <general>: Skipped 2 duplicate messages..
2024-02-17 23:25:22.695 T:9084    error <general>: [plugin.video.youtube] Python strptime bug workaround.
                                                   Refer to https://github.com/python/cpython/issues/71587
2024-02-17 23:25:38.366 T:9084     info <general>: Skipped 2950 duplicate messages..
2024-02-17 23:25:38.366 T:9084     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.3) on Nexus (Kodi-20.3) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'GEGX1H_XlWw'}
2024-02-17 23:25:38.729 T:29704    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=GEGX1H_XlWw
2024-02-17 23:25:38.734 T:12415    info <general>: Creating InputStream
2024-02-17 23:25:39.419 T:12415    info <general>: Creating Demuxer
2024-02-17 23:25:39.737 T:12415    info <general>: Opening stream: 0 source: 256
2024-02-17 23:25:39.737 T:12415    info <general>: Creating video codec with codec id: 27
2024-02-17 23:25:39.738 T:12415    info <general>: CBitstreamConverter::Open bitstream to annexb init
2024-02-17 23:25:39.738 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.aac.decoder
2024-02-17 23:25:39.739 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.amrnb.decoder
2024-02-17 23:25:39.739 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.amrwb.decoder
2024-02-17 23:25:39.740 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.flac.decoder
2024-02-17 23:25:39.740 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.g711.alaw.decoder
2024-02-17 23:25:39.741 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.g711.mlaw.decoder
2024-02-17 23:25:39.741 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.mp3.decoder
2024-02-17 23:25:39.742 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.opus.decoder
2024-02-17 23:25:39.742 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.raw.decoder
2024-02-17 23:25:39.743 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:c2.android.vorbis.decoder
2024-02-17 23:25:39.743 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.vp9.decoder.awesome2
2024-02-17 23:25:39.744 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.ac3
2024-02-17 23:25:39.744 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.dtshd
2024-02-17 23:25:39.745 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.eac3
2024-02-17 23:25:39.745 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.audio.decoder.ffmpeg
2024-02-17 23:25:39.745 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.vp6a.decoder.sw
2024-02-17 23:25:39.746 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.vp6f.decoder.sw
2024-02-17 23:25:39.747 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.avc.decoder.awesome2
2024-02-17 23:25:39.870 T:12415    info <general>: CDVDVideoCodecAndroidMediaCodec:: Open Android MediaCodec OMX.amlogic.avc.decoder.awesome2
2024-02-17 23:25:39.871 T:12415    info <general>: Creating video thread
2024-02-17 23:25:39.880 T:12432    info <general>: running thread: video_thread
2024-02-17 23:25:39.885 T:12415    info <general>: Opening stream: 1 source: 256
2024-02-17 23:25:39.885 T:12415    info <general>: Finding audio codec for: 86018
2024-02-17 23:25:39.887 T:12415    info <general>: CDVDAudioCodecAndroidMediaCodec::Open() Use default handling for non encrypted stream
2024-02-17 23:25:39.888 T:12415    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-02-17 23:25:39.888 T:12415    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-02-17 23:25:39.888 T:12415    info <general>: Creating audio thread
2024-02-17 23:25:39.896 T:12436    info <general>: running thread: CVideoPlayerAudio::Process()
2024-02-17 23:25:39.907 T:12436    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2024-02-17 23:25:39.962 T:29704    info <general>: Instancing CRendererMediaCodecSurface
2024-02-17 23:25:39.962 T:29704    info <general>: CRendererMediaCodecSurface::Configure
2024-02-17 23:25:39.966 T:29725    info <general>: CActiveAESink::OpenSink - initialize sink
2024-02-17 23:25:39.970 T:29725    info <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2024-02-17 23:25:39.973 T:29725    info <general>: Minimum size we need for stream: 30160 Bytes
2024-02-17 23:25:39.973 T:29725    info <general>: Audiotrack buffer params are: period time = 42.744 ms, period size = 15080 bytes, num periods = 4
2024-02-17 23:25:39.973 T:29725    info <general>: Created Audiotrackbuffer with playing time of 170.975057 ms min buffer size: 60320 bytes
2024-02-17 23:25:40.010 T:29725    info <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60320 m_frames: 1885 m_frameSize: 8 channels: 2
2024-02-17 23:25:58.145 T:29672    info <general>: Got MEDIA_BUTTON intent: 127, up:false
2024-02-17 23:25:58.310 T:29672    info <general>: Got MEDIA_BUTTON intent: 127, up:true
2024-02-17 23:26:00.022 T:29672    info <general>: Got MEDIA_BUTTON intent: 86, up:false
2024-02-17 23:26:00.051 T:29704    info <general>: CVideoPlayer::CloseFile()
2024-02-17 23:26:00.052 T:29704    info <general>: VideoPlayer: waiting for threads to exit
2024-02-17 23:26:00.053 T:12415    info <general>: CVideoPlayer::OnExit()
2024-02-17 23:26:00.053 T:12415    info <general>: Closing stream player 1
2024-02-17 23:26:00.053 T:12415    info <general>: Waiting for audio thread to exit
2024-02-17 23:26:00.053 T:12436    info <general>: thread end: CVideoPlayerAudio::OnExit()
2024-02-17 23:26:00.054 T:12415    info <general>: Closing audio device
2024-02-17 23:26:00.145 T:12415    info <general>: Deleting audio codec
2024-02-17 23:26:00.145 T:12415    info <general>: Closing stream player 2
2024-02-17 23:26:00.145 T:12415    info <general>: waiting for video thread to exit
2024-02-17 23:26:00.145 T:12432    info <general>: thread end: video_thread
2024-02-17 23:26:00.146 T:12415    info <general>: deleting video codec
2024-02-17 23:26:00.190 T:29672    info <general>: Got MEDIA_BUTTON intent: 86, up:true
2024-02-17 23:26:00.358 T:29704    info <general>: VideoPlayer: finished waiting
2024-02-17 23:26:00.358 T:29704    info <general>: CVideoPlayer::CloseFile()

**Comment by MoojMidge** [comment] 2024-02-17 22:50
@karlo2105 - can you explain this a bit more?

> It shows viewed video only, but history playback isn't synced with Youtube account.

Where are the viewed videos shown and how is that different to history playback?

Progress is synced during playback and immediately after playback stops. Videos are added to your watched history list if you have this configured.

If something is not working then will need a full debug log showing you starting, playing, then stopping a video. Small bits of a log aren't of much use.

**Comment by karlo2105** [comment] 2024-02-17 23:16
@MoojMidge  
> Where are the viewed videos shown and how is that different to history playback?

Viewed videos are shown in history tab on Youtube web account. Before, when i watched a part of video on YT addon, i was able to resume on Youtube website. 

>  Progress is synced during playback and immediately after playback stops. Videos are added to your watched history list if you have this configured.

With YT 7.0.1, progress used to be synced with YT account. With 7.0.3.beta.3, watched video is listed only on history tab within YT website. Progress is not taken at all into account. 

> If something is not working then will need a full debug log showing you starting, playing, then stopping a video. Small bits of a log aren't of much use.

I have several banned addons installed that's why i only put YT debug log. How can i provide full debug log? Are you able to check at your side that video progress isn't taken into account on Youtube website?

**Comment by MoojMidge** [comment] 2024-02-18 00:21
> With YT 7.0.1, progress used to be synced with YT account. With 7.0.3.beta.3, watched video is listed only on history tab within YT website. Progress is not taken at all into account

Ok, I understand now.

> Are you able to check at your side that video progress isn't taken into account on Youtube website?

Nope, the account I use for development doesn't have YouTube history enabled and my network blocks `s.youtube.com` as well.

> How can i provide full debug log?

https://kodi.wiki/view/Log_file/Easy

Need the content of the log from when you open the Youtube plugin, start playing a video, and then stop the video. Without that can't do much.

**Comment by victore447** [comment] 2024-02-18 00:57
> @victore447 - What does that have to do with this issue?
> 
> Please try to search before creating new issues or responding to unrelated issues.
> 
> You haven't set up your OAuth access correctly. See #204

👋Whatever the API configuration web tutorials use, the blocking is there and there is also a context menu sending me to the Github Youtube Repo.  (Attached photo).
[Wiki.tecalbox
![page](https://github.com/anxdpanic/plugin.video.youtube/assets/48101775/c84cca64-0d91-4ff9-b91f-327a6c04eed8)
](https://wiki.recalbox.com/en/tutorials/kodi/youtube-add-on-configuration)
 **My old Google Console API configuration remained active for over two years without me having to change anything.**
Finally I know the plugin since I have been using it for over 10 years without having had the need to contact you ✔️

**Comment by MoojMidge** [comment] 2024-02-18 07:35
@victore447 - Your first screenshot referred to a specific error with the client/project OAuth  credentials you setup. The fix for this is documented in #204

Your second screenshot indicates another specific issue with your OAuth credentials, that is all quite self explanatory.

But if your experience tells you something different, then you are probably better off resolving the issue yourself rather than seeking help here.

Regardless, this issue you are commenting in is completely unrelated, and I would ask that you refrain from continuing to derail the conversation.

**Comment by victore447** [comment] 2024-02-18 11:07
> @victore447 - Your first screenshot referred to a specific error with the client/project OAuth credentials you setup. The fix for this is documented in #204
> 
> Your second screenshot indicates another specific issue with your OAuth credentials, that is all quite self explanatory.
> 
> But if your experience tells you something different, then you are probably better off resolving the issue yourself rather than seeking help here.
> 
> Regardless, this issue you are commenting in is completely unrelated, and I would ask that you refrain from continuing to derail the conversation.

👋Without being connected, the videos work on it.
  I deduce that like the majority of Kodi addons published online ( [Iwf1](https://iwf1.com/kodi) ,[Kodiapps](https://kodiapps.com/) , [Github](https://github.com/) ....) you do not want to recognize that the YouTube video plugin is also now out of service  there and it is currently blocked from connecting to it.

 _I'll settle for [Smarttubeapp](https://smarttubeapp.github.io/) .....on Android which does the job just as well (ad blocking) as the YouTube Kodi video plugin ☝️and will never bother you again._
 **Strange your ways of responding coldly to people ✔️**

**Comment by karlo2105** [comment] 2024-02-18 12:19
@MoojMidge

> Need the content of the log from when you open the Youtube plugin, start playing a video, and then stop the video. Without that can't do much.

Log with opened Youtube ; 
https://paste.kodi.tv/ekibenotoj

Log after playing a video on Youtube :
https://paste.kodi.tv/tabeqowuve

I hope it helps.

**Comment by MoojMidge** [comment] 2024-02-19 01:34
@victore447 - you can do what you want, but I can't help you if you don't even try to listen, just because you think you know better. It is also quite rude to keep on butting in to a completely unrelated discussion like you are doing.

Something you may not understand is that those errors you are getting are coming straight from Google/Youtube, and they very specifically indicate that there are problems with the OAuth credentials that you have created.

You may not have done anything with the credentials in 2 years, but neither has this plugin. Do you know who can change things with the created credentials? Google/Youtube can, and they are telling you exactly that.

So you can try to argue with me about it because you have used the plugin for 10 years, or use another app, or do whatever, but the only solution is to recreate the credentials and do it properly.

**Comment by MoojMidge** [comment] 2024-02-19 01:48
@karlo2105 - Thanks for that, helps clear things up.

Unfortunately the logs indicate the following:

1. You don't have a history playlist set up in the plugin settings, so nothing can be added to your playback history. It is not straightforward to get this to work, and this wouldn't have worked in v7.0.1 either, unless you know what your history playlist ID is (or used some other different playlist ID) and also entered it into the plugin settings.
2. The progress tracking does appear to be working.

So the plugin seems to be the working correctly, but doing the opposite of what you are describing.

As I don't actually use this functionality I don't know what the expected behaviour is with regards to the progress tracking, but from what I can understand it is not intended to automatically add things to your watched history list.

Will probably need someone else to confirm whether they are also seeing this kind of problem.

**Comment by MoojMidge** [comment] 2024-02-24 10:03
Was travelling and was able to test this myself.

The progress tracking worked and it also added the in-progress video to my Youtube history.

Your logs also indicate that the plugin is doing what it is supposed to, so not sure what the problem may be.

**Comment by karlo2105** [comment] 2024-02-24 10:24
@MoojMidge
With 7.0.1, progress tracking worked fine. When i started a video in YT addon, i was able to resume on Youtube web from stopped time. Now it only lists viewed videos in history without progress at all. I updated to 7.0.3.beta4. I erased json key and logged again and it doesn't change anything regarding progress video in history.

**Comment by MoojMidge** [comment] 2024-02-24 13:40
Not sure how it would have worked any differently in v7.0.1, but I will take your word for it that it did.

In any case I can see why it wouldn't work now, I never committed the changes required to make it work. The next beta should fix it.

**Closed as completed** 2024-02-24 14:16 UTC
Labels: bug

**Comment by jemiller00** [comment] 2024-12-21 02:14
Did this fix ever make it into production? My history is not being updated on the website.

**Comment by MoojMidge** [comment] 2024-12-21 04:55
> Did this fix ever make it into production? My history is not being updated on the website.

Yes. I already asked you for details in #1033. Please don't continue to post in unrelated issues, let's try to keep things together rather than looking in a bunch of different places
