### ISSUE TITLE
Error playing any YouTube video

### ISSUE THREAD

**Issue by CrashM85** [anxdpanic/plugin.video.youtube#592] opened 2024-02-24 13:58 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: (Kodi-20.3) with Python 3.9.2
* Kodi GUI Language: English
* Operating System: OSMC
* Operating System Language: English

Setup with API key and signed in.

------

### Expected Behavior

Playing any YouTube video

------

### Current Behavior

Fails to play

------

### Steps to Reproduce

1. Play any YouTube video

------

### Log

2024-02-24 13:52:38.014 T:2376     info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.3) with Python 3.9.2
                                                        Path: /play/
                                                        Params: {'video_id': 'ahdh1E1FvJk'}
2024-02-24 13:52:38.154 T:2376    error <general>: [plugin.video.youtube] Player response failed for video_id: ahdh1E1FvJk, using android client (logged in)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player

2024-02-24 13:52:38.155 T:2376    error <general>: Traceback (most recent call last):

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _request
                                                       result.raise_for_status()

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.youtube.com/youtubei/v1/player

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:
                                                   The above exception was the direct cause of the following exception:

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>: Traceback (most recent call last):

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                       video_streams = client.get_video_streams(context, video_id)

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 102, in get_video_streams
                                                       video_streams = video_info.load_stream_infos(video_id)

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 883, in load_stream_infos
                                                       return self._get_video_info()

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1323, in _get_video_info
                                                       result = self._request(

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 937, in _request
                                                       raise YouTubeException(error_msg) from error

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>: youtube_plugin.youtube.youtube_exceptions.YouTubeException: Player response failed for video_id: ahdh1E1FvJk, using android client (logged in)

2024-02-24 13:52:38.156 T:2376    error <general>:
2024-02-24 13:52:38.156 T:2376    error <general>: [plugin.video.youtube] None
2024-02-24 13:52:38.160 T:448     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=ahdh1E1FvJk]

------

### Additional Information

Tried installing the latest beta version but got the following error instead:

2024-02-24 13:35:26.882 T:1555     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.4+matrix.1) on Nexus (Kodi-20.3) with Python 3.9.2
                                                   Path: /
                                                   Params: {}
2024-02-24 13:35:26.934 T:1555  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-02-24 13:35:26.936 T:1555    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'ListItemInfoTag' is not defined
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 17, in <module>
                                                       plugin_runner.run(youtube.Provider())
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 60, in run
                                                       __PLUGIN__.run(provider, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 88, in run
                                                       items = [
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 89, in <listcomp>
                                                       directory_listitem(context, item, show_fanart)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 382, in directory_listitem
                                                       set_info_tag(list_item, item_info, 'video')
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/compatibility/__init__.py", line 17, in set_info_tag
                                                       return ListItemInfoTag(listitem, tag_type)
                                                   NameError: name 'ListItemInfoTag' is not defined
                                                   -->End of Python script error report<--

2024-02-24 13:35:27.056 T:1554    error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2024-02-24 13:35:27.071 T:448     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed

------

**Comment by MoojMidge** [comment] 2024-02-24 14:03
Duplicate of #582

**Closed as completed by MoojMidge** 2024-02-24 14:03 UTC
Labels: bug

**Comment by MoojMidge** [comment] 2024-02-24 14:05
> 2024-02-24 13:35:26.882 T:1555 info : [plugin.video.youtube] Running: YouTube (7.0.3+beta.4+matrix.1) on Nexus (Kodi-20.3) with Python 3.9.2

The reason the beta is not working is because you have installed the Kodi 19 (Matrix) version on Kodi 20 (Nexus)

**Comment by CrashM85** [comment] 2024-02-24 14:14
Thanks, sorry for the duplicate, though i can confirm i'm running Kodi 20.3 and Beta 4 doesn't seem to be working:

2024-02-24 14:12:05.967 T:3579     info <general>: CAddonMgr::FindAddon: plugin.video.youtube v7.0.3+beta.4+matrix.1 installed
2024-02-24 14:12:10.777 T:3583     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.4+matrix.1) on Nexus (Kodi-20.3) with Python 3.9.2
                                                   Path: /sign/out/
                                                   Params: {'confirmed': True}
2024-02-24 14:12:11.981 T:448     error <general>: Control 50 in window 10025 has been asked to focus, but it can't
2024-02-24 14:12:15.416 T:3603     info <general>: [plugin.video.youtube] Running: YouTube (7.0.3+beta.4+matrix.1) on Nexus (Kodi-20.3) with Python 3.9.2
                                                   Path: /
                                                   Params: {}
2024-02-24 14:12:15.442 T:3603  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-02-24 14:12:15.445 T:3603    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'ListItemInfoTag' is not defined
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 17, in <module>
                                                       plugin_runner.run(youtube.Provider())
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 60, in run
                                                       __PLUGIN__.run(provider, context)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 88, in run
                                                       items = [
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 89, in <listcomp>
                                                       directory_listitem(context, item, show_fanart)
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/items/xbmc/xbmc_items.py", line 382, in directory_listitem
                                                       set_info_tag(list_item, item_info, 'video')
                                                     File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/compatibility/__init__.py", line 17, in set_info_tag
                                                       return ListItemInfoTag(listitem, tag_type)
                                                   NameError: name 'ListItemInfoTag' is not defined
                                                   -->End of Python script error report<--

2024-02-24 14:12:15.588 T:3602    error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/
2024-02-24 14:12:15.589 T:448     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed

**Comment by CrashM85** [comment] 2024-02-24 14:23
Thanks, appologies for the duplicate.
