### ISSUE TITLE
The following content is not available on this app.

### ISSUE THREAD

**Issue by jsox79** [anxdpanic/plugin.video.youtube#676] opened 2024-04-02 04:08 UTC
### Context
Says app is outdated.

Please provide any relevant information about your setup

* Add-on Version: latest 7.04
* Kodi Version: 20.3
* Kodi GUI Language: English
* Operating System: Windows 11
* Operating System Language: English
* 

------

### Expected Behavior

Please describe the behavior you are expecting.

------

### Current Behavior

What is the current behavior?

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. 
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment] 2024-04-02 04:22
Duplicate of #654, #659, #663

Use: 
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.5%2Bbeta.4

**Closed as not planned by MoojMidge** 2024-04-02 04:22 UTC
Labels: bug
