### ISSUE TITLE
&order=$ORDER parameter for playlists not working

### ISSUE THREAD

**Issue by siennamediatest** [anxdpanic/plugin.video.youtube#621] opened 2024-03-11 03:02 UTC
Using the 7.0.3.2 version. 
I use the timers addon and also have a gpio button press that activates youtube playlists. Usually it's music playing in random order for old folks at a retirement home. For some reason when I input this it there's now a popup window that asks me to select playlist order. I just want the playlist to play automatically, so should the &order work?

xbmc.executebuiltin("RunPlugin(plugin://plugin.video.youtube/play/?playlist_id=PLopMpzJBXsBTw6PGe3ZZrppJJfm22BlDW&order=shuffle&play=1)")

**Comment by MoojMidge** [comment] 2024-03-11 04:53
Duplicate of #607

**Comment by MoojMidge** [comment] 2024-03-11 04:54
Can apply the linked fix yourself, or wait until the next release

**Closed as completed by MoojMidge** 2024-03-11 04:54 UTC
Labels: bug

**Comment by MoojMidge** [comment] 2024-03-13 00:34
[v7.0.4+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.1) is available to test and should fix this issue.

**Comment by siennamediatest** [comment] 2024-03-19 15:02
great- I will test it later today

**Comment by siennamediatest** [comment] 2024-03-26 23:20
> [v7.0.4+beta.1](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.4%2Bbeta.1) is available to test and should fix this issue.

I'm running 7.0.4 with nexus and matrix on different systems- YouTube won't play all on a playlist, and if I call a YouTube playlist via gpio press, it doesn't work. Just ends up with a spinning icon and never plays.

**Comment by MoojMidge** [comment] 2024-03-26 23:34
What you are now describing is different to what you originally described.

When you fill in a bug report, the information you are required to provide is identified.

Nothing can be done when you don't provide this information.

**Comment by siennamediatest** [comment] 2024-03-27 16:03
sorry. Original issue was fixed but there's a worse/related issue now in the latest version. I will update with proper info.
