### ISSUE TITLE
Selecting to play a (previously partly watched) video from beginning resumes from previous left off instead to start from begin

### ISSUE THREAD

**Issue by jcjdammers** [anxdpanic/plugin.video.youtube#814] opened 2024-06-22 15:56 UTC
When I have partly watched a video (from my liked videos list), then stop it before it ends, and then select it later again for watching, then I get a popup menu with two options: resume from the timestamp that I left off previously, or start from the beginning.
When I select start from the beginning then it always resumes to play from where I left off instead of to start from the beginning.

I use LibreELEC 12.0 with Kodi (Omega) v21.0.
I have latest version of the plugin 7.0.5.

Regards,
Jeroen

**Comment by MoojMidge** [comment] 2024-06-22 21:19
Duplicate of #693

**Closed as not planned by MoojMidge** 2024-06-22 21:19 UTC
Labels: bug
