### ISSUE TITLE
"Playback failed" from stopped playlist

### ISSUE THREAD

**Issue by timur-davletshin** [anxdpanic/plugin.video.youtube#810] opened 2024-06-21 10:30 UTC
* Add-on Version: 7.0.8 beta 3
* Kodi Version: 21.0
* Kodi GUI Language: English
* Operating System: Libreelec 12.0
* Operating System Language: English
* Reproducible: Yes

Open any YouTube video -> Stop it -> Open left panel -> Click Go to playlist -> Start playback of recently stopped video  = Error popup "Playback failed".

**Comment by MoojMidge** [comment] 2024-06-21 10:55
I'm going to assume that this has nothing to do with playing from a stopped playlist, and is just a duplicate of a bunch of other similar reports about playback sometimes not working.

Probably fixed in https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8%2Bbeta.4

If not post a debug log.

Edit: Looks like the same problem but different consequence because of playback being started from the playlist window and Kodi not respecting the `ForceResolvePlugin` property. Not much I can do about it at this stage.

**Comment by neo-neo1** [comment] 2024-06-27 01:03
Yep, known problem. Same exact issue I've had for several versions. It did go away a few versions ago, but the newest version has it occurring quite frequently.

**Comment by MoojMidge** [comment] 2024-06-27 12:28
> Yep, known problem. Same exact issue I've had for several versions. It did go away a few versions ago, but the newest version has it occurring quite frequently.

That doesn't seem likely since the bug that timur-davletshin has identified would have only started occurring in v7.0.7

**Comment by MoojMidge** [comment] 2024-07-27 05:07
Disable the following new setting as a workaround in [v7.0.9+beta.5](https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.9%2Bbeta.5):
`Settings > Advanced > HTTP Server > Allow idle shutdown`

**Closed as completed by MoojMidge** 2024-07-27 05:07 UTC
Labels: bug

**Comment by neo-neo1** [comment] 2024-08-01 12:38
Same exact problem exists in 7.0.9 Beta 5. Reopen this issue.

Unfortunately playlist is a complete and utter buggy mess.

**Comment by neo-neo1** [comment] 2024-08-01 12:39
Same exact problem exists in 7.0.9 Beta 5. Reopen this issue @MoojMidge 

Unfortunately playlist is a complete and utter buggy mess.

**Comment by MoojMidge** [comment] 2024-08-03 02:38
Create a new issue with a log and I will have a look when I have some time.

**Comment by neo-neo1** [comment] 2024-08-04 06:23
I already included details instructed on how to replicate it. 👍

**Comment by MoojMidge** [comment] 2024-08-04 07:38
Can't replicate. No log, no problem.
