### ISSUE TITLE
Subtitle Python script error reported

### ISSUE THREAD

**Issue by samsonluk** [anxdpanic/plugin.video.youtube#550] opened 2023-12-27 10:05 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.2.2
* Kodi Version: 20.2
* Kodi GUI Language: English 
* Operating System: Android 11
* Operating System Language: English 

------

### Expected Behavior

Video playback with selected subtitle. 

------

### Current Behavior

Generated a "YouTube error, check the log for more information." Video failed to playback.

------

### Steps to Reproduce

1. Choosing "Play with subtitles"
2. Selecting any available subtitle to play
3. 

------

### Log

File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 146, in get_subtitles
                                                       return self._prompt()
                                                              ^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py", line 171, in _prompt
                                                       return self._get(language=languages[choice][0], language_name=languages[choice][1])
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: Subtitles._get() got an unexpected keyword argument 'language_name'
                                                   -->End of Python script error report<--
                                                   
2023-12-27 09:08:46.430 T:31622 warning <CAddonSettings[0@plugin.video.youtube]>: failed to load value "8" for setting kodion.mpd.quality.selection
2023-12-27 09:08:46.452 T:31622    info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.2) on N***** (Kodi-20.2) with Python 3.11.2
                                                   	Path: /play/
                                                   	Params: {'video_id': 'Q96A6pJ2h6I'}

------

### Additional Information

Please provide any additional information that may be helpful.

Also failed with the same error on an Android TV 12 with the same version of Kodi and YouTube Plugin.

------

**Comment by MoojMidge** [comment] 2023-12-27 10:43
Duplicate of https://github.com/anxdpanic/plugin.video.youtube/issues/534

**Closed as completed by MoojMidge** 2023-12-27 10:43 UTC
Labels: bug
