### ISSUE TITLE
Unable to enter My Subscritions list

### ISSUE THREAD

**Issue by Juppstein** [anxdpanic/plugin.video.youtube#499] opened 2023-08-02 11:06 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version:  7.0.1
* Kodi Version:  20.2
* Kodi GUI Language: German
* Operating System: Ubuntu 22.04
* Operating System Language: English

------

### Expected Behavior

Opening Addon and entering subscribed youtube video list  (My Subscriptions/Meine Abonnements) gives list of latest video of subscribed accounts

------

### Current Behavior

As of today morning I am suddenly not able to go to my subscriptions feed anymore. The addon loads for about 10 seconds and then shows an empty list. This worked up until yesterday evening. I removed the addon, deleted all userdata for the addon and installed it again but the problem persists. Looking at the log file the addon loads properly but throws hundreds of error messages as soon as I go to my subscription feed for new videos. Going to the list of subscribed youtube accounts and then starting videos from there works as well as the popular vid feed. 

Here is the paste of the log file from the moment I select the subbed videos menu:

​​​​​​​https://paste.kodi.tv/unicozeyat.kodi

**Comment by MoojMidge** [comment] 2023-08-08 12:02
Duplicate of #280

**Comment by MoojMidge** [comment] 2023-08-08 12:02
Download latest version of the plugin (follow [these instructions](https://github.com/anxdpanic/plugin.video.youtube/issues/495#issuecomment-1629796150)) and install manually until a new release is pushed out.

**Closed as completed by MoojMidge** 2023-08-08 12:02 UTC
Labels: bug
