### ISSUE TITLE
Error installing plugin youtube 7.1.1+beta.5.leia.1

### ISSUE THREAD

**Issue by BarrelGun** [anxdpanic/plugin.video.youtube#968] opened 2024-11-12 17:52 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.1+beta.5.leia.1
* Kodi Version: (18.9 (18.9.0) Git:0655c2c)
* Kodi GUI Language: Ru
* Operating System: AlexELEC-3.3.9 (S9XX-DualBoot.arm)
* Operating System Language: Ru

------

### Expected Behavior
Installing the YouTube plugin
------

### Current Behavior
When trying to install the plugin version 7.1.1+beta.5.leia.1 an error occurs

------

### Steps to Reproduce

1. I'm entering the add-ons
2. Install from file zip
3. I select the file plugin.video.youtube-7.0.5+beta.4.leia.1.zip
4. I get an error...
------
### Log
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name InvalidJSONError
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/service.py", line 13, in <module>
                                                from youtube_plugin.kodion import service_runner
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/service_runner.py", line 20, in <module>
                                                from .monitors import PlayerMonitor, ServiceMonitor
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/__init__.py", line 14, in <module>
                                                from .service_monitor import ServiceMonitor
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/service_monitor.py", line 27, in <module>
                                                from ..network import get_connect_address, get_http_server, httpd_status
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/__init__.py", line 12, in <module>
                                                from .http_server import (
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/http_server.py", line 19, in <module>
                                                from .requests import BaseRequestsClass
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 18, in <module>
                                                from requests.exceptions import InvalidJSONError, RequestException
                                            ImportError: cannot import name InvalidJSONError
                                            -->End of Python script error report<--

------
### Additional Information
On previous versions of the plugin there was also an error during installation

------

**Comment by MoojMidge** [comment] 2024-11-12 18:54
Duplicate of #610

Minimum required version of requests:
https://github.com/anxdpanic/plugin.video.youtube/pull/612/files

**Closed as not planned by MoojMidge** 2024-11-12 18:54 UTC
Labels: bug

**Comment by BarrelGun** [comment] 2024-11-13 05:54
Installed script.module.requests-2.27.1 and other dependent modules... And everything worked! Thanks, friend!

**Comment by MoojMidge** [comment] 2024-11-13 06:25
Glad you got it sorted. What version are the dependencies you installed?

**Comment by BarrelGun** [comment] 2024-11-13 06:56
During the installation of script.module.requests-2.27.1, messages pop up about installing necessary add-ons.
I downloaded and installed them:
script.module.certifi-2021.10.8.zip
script.module.chardet-4.0.0.zip
script.module.idna-2.10.0.zip
script.module.urllib3-1.26.18.zip

**Comment by MoojMidge** [comment] 2024-11-13 10:01
How about inputstream.adaptive? What version of that is available for your system?

**Comment by BarrelGun** [comment] 2024-11-13 17:03
By default, my system has inputstream.adaptive version 2.4.4.1 installed. When I enable it, I can't get into the settings of this add-on from the YouTube menu.
When watching videos, I use 720P resolution, because in my country, very smart people decided to slow down YouTube for some reason (sarcasm).
The only inconvenience is that when watching a live broadcast, I can't rewind the video to the beginning. Maybe I should play with the YouTube plugin settings or update the inputstream.adaptive version (but I couldn't find an updated version of the plugin for Kodi 18.9 anywhere).
Nevertheless, I am very glad and happy that I can watch videos on the updated version of the YouTube plugin and I convey my gratitude and respect to the developers!

**Comment by MoojMidge** [comment] 2024-11-14 22:31
> When I enable it, I can't get into the settings of this add-on from the YouTube menu.

Yes that is expected when using Kodi 18, you can do so from the addon manager, but you shouldn't really need to change any settings in the InputStream.Adaptive settings.

> The only inconvenience is that when watching a live broadcast, I can't rewind the video to the beginning.

That is also to be expected when using Kodi 18, it can also be a bit problematic in newer version as well.

> Nevertheless, I am very glad and happy that I can watch videos on the updated version of the YouTube plugin and I convey my gratitude and respect to the developers!

👍
