### ISSUE TITLE
Live Streams Pause on Last Frame

### ISSUE THREAD

**Issue by neo-neo1** [anxdpanic/plugin.video.youtube#674] opened 2024-04-01 22:00 UTC
### Context

* Add-on Version: 7.0.5 Beta 2
* Kodi Version: 20.5
* Kodi GUI Language: English 
* Operating System: CoreELEC
* Operating System Language: English
* YouTube settings are on default.

------

### Expected Behavior

When watching a Live Stream from Queue the video pauses on the last frame when the live stream ends. It does not end the video as expected. This causes the next video in queue to not start playing.

------

### Steps to Reproduce

1. Add a currently playing live stream to queue. 
2. Add any other video after it to queue 
3. Play the live stream from Queue.
4. When the live stream ends the video will pause on last frame.

Note: I did not get a chance yet to test if playing a YouTube live stream directly (not from queue) causes the same problem or not. I'm presunimg the issue also occurs when playing a live stream directly - will verify soon.

------

### Log

Can provide log later if requested. I'm assuming this isn't a unique problem and able to be replicated.

------

As always thanks to Mooj for his upkeep

**Comment by MoojMidge** [comment] 2024-04-02 03:51
Will need a debug log.

It is likely an issue with InputStream.Adaptive, that may have improved with more recent versions, however need to check what plugin settings are being used, and what the actual log details from InputStream.Adaptive are.

I have very limited capacity to work on this, let alone time to hunt down a recently finishing live stream, then wait for it to finish, in order to check log details that you will already have, which may or may not be able to be replicated.

If there are problems, then I need your input to resolve them.

**Comment by audiosistem** [comment] 2024-04-03 06:04
Hello!In relation to the played streams.Everything is functional with the latest version in the addon.
But put in the widget a topic from the search.Kodi crashes.Win 64/kodi 20.5/HP Elitebook.Dependencies installed and configured.Everything is functional, I repeat, in the addon.I'm thinking about the skin.But collapse in Aeon, Zephyr, Arctic, Fuse...any suggestion?Thank you!

**Comment by MoojMidge** [comment] 2024-04-04 01:11
> any suggestion?

Create a new issue, fill in all the required information and include a debug log, so it can be looked into. This issue is completely unrelated.

**Comment by MoojMidge** [comment] 2024-04-26 23:21
@neo-neo1 - can you check whether this still happens when doing the following?

- Update to Kodi v21
- Update to InputStream.Adaptive v21.4.5 or later
- Use https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.6
- Run the Setup Wizard and confirm Step 1 to change settings to recommended values

**Comment by neo-neo1** [comment] 2024-04-29 04:53
> @neo-neo1 - can you check whether this still happens when doing the following?
> 
>     * Update to Kodi v21
> 
>     * Update to InputStream.Adaptive v21.4.5 or later
> 
>     * Use https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.6
> 
>     * Run the Setup Wizard and confirm Step 1 to change settings to recommended values

For what it's worth I just played a live video on Adaptive HLS and the issue is still there. 

On Kodi 20.

**Comment by MoojMidge** [comment] 2024-04-30 05:30
I'm going to close this. Without a debug log can't determine anything and I can't reproduce the issue in Kodi 21.

If it only happens in Kodi 20, then it is probably not going to be fixed as the changes in the InputStream.Adaptive v21+ are unlikely to be backported.

**Closed as completed by MoojMidge** 2024-04-30 05:30 UTC
Labels: bug

**Comment by neo-neo1** [comment] 2024-05-01 22:38
So I upgraded to Kodi 21 and this problem went away. MPEG-DASH on live & premiere videos works fine on Kodi 21. Adaptive HLS would be the right choice for Kodi 20 by default.

Still have the other problem of playlist disappearing occasionally.

**Comment by MoojMidge** [comment] 2024-05-01 23:54
> Still have the other problem of playlist disappearing occasionally.

What is that one?
