### ISSUE TITLE
Not all HLS Streams Are Displayed, Making HDR Playback Broken In Many Cases

### ISSUE THREAD

**Issue by ilikenwf** [anxdpanic/plugin.video.youtube#531] opened 2023-11-02 07:54 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.0.1
* Kodi Version: 20.x and 21 Beta1
* Kodi GUI Language: EN
* Operating System: Linux
* Operating System Language:EN

So, I have an intel ARC card, and from what I can tell, though, it doesn't necessarily appear to be the issue at hand here.

If I enable DASH, and have the addon set to 4k VP9 HDR, playback results in a black screen. If I disable HDR, I get playback. Then, if I use yt-dlp or a test plugin by Slyguy for youtube, I can play back the 4k vp9 HDR video without an issue.

Ongoing discussion here https://github.com/xbmc/inputstream.adaptive/issues/1410

I think there's HLS and stream selection issues at hand, as there are many more possible streams if you pull the list of them down with yt-dlp than are able to be selected in the addon - HDR support should also span other codecs, should it not?

Regardless, the test video I've been using is this one, which results in a black screen:

https://www.youtube.com/watch?v=VO8Bk03Xv90

Even if my card is having issues, the fact that the vp9 HDR streams that I can select with yt-dlp or slyguy's plugin indicates that there should be more/other format options.

Thank you!

------

### Expected Behavior

HDR Video Playback to function properly

------

### Current Behavior

Black screen or a "ghost" afterimage of the last kodi screen I was on.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Be me, with an Arc A380, DASH enabled, vp9 2k HDR
2.  Play a video
3.  Black screen

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

https://github.com/xbmc/xbmc/files/13187045/kodi.log.zip

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by ilikenwf** [comment] 2023-11-02 08:12
And I did install your test version...while it does at least let me play everything in 4k again by disabling HDR, it unfortunately does not fix this issue.

**Comment by ilikenwf** [comment] 2023-11-02 08:15
And I can confirm the version I grabbed with yt-dlp is HDR via ffmpeg:

```
Input #0, matroska,webm, from 'Obi-Wan - Obi-Wan vs Darth Vader - (HDR - 4K - 5.1) [VO8Bk03Xv90].mkv':
  Metadata:
    ENCODER         : Lavf60.15.100
  Duration: 00:09:16.16, start: 0.000000, bitrate: 22490 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 2), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:09:16.083000000
    Side data:
      Mastering Display Metadata, has_primaries:1 has_luminance:1 r(0.7080,0.2920) g(0.1700,0.7970) b(0.1310 0.0460) wp(0.3127, 0.3290) min_luminance=0.000000, max_luminance=1000.000000
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, 5.1, fltp (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:09:16.160000000
```

**Comment by MoojMidge** [comment] 2023-11-02 09:47
There are a few misunderstandings in that InputStream.Adaptive thread, so I will provide more details there.

> And I did install your test version...

If you mean something from https://github.com/MoojMidge/plugin.video.youtube/tree/master, that is generally not a good idea, because I push and rebase in that repository without any testing. If it currently works, then OK, but it is a better idea to just stick with the latest official release: https://github.com/anxdpanic/plugin.video.youtube/releases/latest

**Comment by MoojMidge** [comment] 2023-11-02 10:31
In the meantine I will close this, the plugin has nothing to do with whether or not your device can display HDR video, and the latest official version allows you to select whatever resolution and stream features you want. HLS streams are not used at the moment for VODs but as far as I know there are no HDR enabled HLS streams anyway.

**Closed as completed by MoojMidge** 2023-11-02 10:31 UTC
Labels: bug

**Comment by ilikenwf** [comment] 2023-12-16 12:09
@MoojMidge so I fixed my first HDR issue: arch and the pkgbuild for DIY building Kodi both are using gl instead of gles...so now I have HDR playback of nearly everything...except youtube, haha.

Enabling it still results in this issue. Seems that it may be a vp9 hardware decoding issue.

**Comment by ilikenwf** [comment] 2023-12-16 12:12
...turning off VP9 hardware decoding works at least for some youtube videos, so I'm not sure now if I should talk to the kodi devs, ffmpeg, or intel...fun!

**Comment by MoojMidge** [comment] 2023-12-16 22:31
This issue is not a bug with this plugin and was closed. I have already responded at length, in your other linked issue, with what I suggest you should do.

Not sure what you expect from anyone, when there are still no comparative logs for the video that worked (did it actually work?) and the others that didn't, no samples, or even media info, for anyone to look at.

I already pointed out, based on the scraps of information that you are providing, that both the HDR metadata and video framerates are different, for the streams that (maybe?) worked compared to ones that didn't work, on what should otherwise be the same video.

I have nothing further to add.

**Comment by ilikenwf** [comment] 2023-12-16 22:33
I was just following up. If someone lands here from a search and wastes their time reading to the end with no resolution, it's a good way to get pissed off.

**Comment by MoojMidge** [comment] 2023-12-16 22:53
Okay? But like I said, if you really wanted to follow up, you need to go about it in a way that will actually provide useful information. A member of the Kodi team has also responded suggesting the same.
