### ISSUE TITLE
Unable to Sign in

### ISSUE THREAD

**Issue by Eontech** [anxdpanic/plugin.video.youtube#760] opened 2024-05-16 16:57 UTC
### Context

* Add-on Version: 7.0.7+beta.1
* Kodi Version: 20.2
* Kodi GUI Language: English
* Operating System: Ubuntu 20.04.6
* Operating System Language: English UK

------

### Expected Behavior

Sign back in using the new 7.0.7 (forced update after getting kicked out of 7.0.3.2)

------

### Current Behavior

Fails to sign in after successfully entering both codes with google.com/device

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Update the OS, then Update to 7.0.6.2 (or / then 7.0.7+beta.1)
2. Go through the wizard / lose recent search history / find it's replaced with an older search history
3. Fail to Sign in

------

### Log

```console
...
2024-05-16 17:59:34.173 T:3056357   error <general>: Skipped 1 duplicate messages..
2024-05-16 17:59:34.173 T:3056357   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-Kodi| client_id: |477...t.com| client_secret: |GOC...5Mt|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 17:59:39.652 T:3056357   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: int() argument must be a string, a bytes-like object or a number, not 'tuple'
                                                   Traceback (most recent call last):
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 63, in run
                                                       plugin.run(provider, context)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 156, in run
                                                       result, options = provider.navigate(context)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 142, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 345, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 755, in _on_sign
                                                       yt_login.process(mode, self, context)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_login.py", line 181, in process
                                                       access_manager.update_access_token(
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/access_manager.py", line 429, in update_access_token
                                                       current_user['token_expires'] = int(unix_timestamp)
                                                   TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
                                                   -->End of Python script error report<--

2024-05-16 17:59:39.668 T:3051747    info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-16 17:59:39.757 T:3056360   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/sign/in/?category_label=Sign%20In
2024-05-16 17:59:39.765 T:3051715   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/sign/in/?category_label=Sign%20In) failed
2024-05-16 17:59:40.266 T:3056621    info <general>: [plugin.video.youtube] Running: YouTube (7.0.7+beta.1) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /
                                                   Params: {}
2024-05-16 17:59:40.654 T:3051747    info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_02.0.hdmi-stereo in pcm mode with Buffersize 200 ms Periodsize 50 ms
2024-05-16 18:05:29.786 T:3058197    info <general>: WEATHER: Downloading weather
2024-05-16 18:14:16.637 T:3051747    info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-16 18:14:17.616 T:3051747    info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_02.0.hdmi-stereo in pcm mode with Buffersize 200 ms Periodsize 50 ms
2024-05-16 18:14:21.205 T:3059964    info <general>: [plugin.video.youtube] Running: YouTube (7.0.7+beta.1) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /config/youtube/
                                                   Params: {'category_label': 'Settings'}
2024-05-16 18:14:21.207 T:3059962   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/config/youtube/?category_label=Settings
2024-05-16 18:14:21.220 T:3051715   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/config/youtube/?category_label=Settings) failed
2024-05-16 18:14:21.283 T:3059964    info <general>: [plugin.video.youtube] Running: YouTube (7.0.7+beta.1) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /
                                                   Params: {}
2024-05-16 18:15:22.324 T:3061067    info <general>: [plugin.video.youtube] Running: YouTube (7.0.7+beta.1) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /
                                                   Params: {}
2024-05-16 18:15:29.741 T:3061067    info <general>: [plugin.video.youtube] Running: YouTube (7.0.7+beta.1) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /sign/in/
                                                   Params: {'category_label': 'Sign In'}
2024-05-16 18:15:29.919 T:3061067   error <general>: [plugin.video.youtube] Logout Failed
                                                   Revoke failed: "error" in response JSON data
                                                   Request response:
                                                   {'error': 'invalid_request', 'error_description': 'Bad Request', 'code': 400}
2024-05-16 18:15:33.141 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:15:43.404 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:15:43.404 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:15:53.660 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:15:53.660 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:16:03.922 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:16:03.922 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:16:14.179 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:16:14.179 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:16:24.450 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:16:24.450 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:16:34.710 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:16:34.710 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-TV| client_id: |861...t.com| client_secret: |Sbo...XAT|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:16:45.643 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:16:45.643 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-Kodi| client_id: |477...t.com| client_secret: |GOC...5Mt|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:16:55.936 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:16:55.936 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-Kodi| client_id: |477...t.com| client_secret: |GOC...5Mt|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:17:06.219 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:17:06.219 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-Kodi| client_id: |477...t.com| client_secret: |GOC...5Mt|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:17:16.536 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:17:16.536 T:3061067   error <general>: [plugin.video.youtube] Login Failed: Unknown response
                                                   Access token request failed (config_type: |YouTube-Kodi| client_id: |477...t.com| client_secret: |GOC...5Mt|):
                                                   "error" in response JSON data
                                                   Request response:
                                                   {'error': 'authorization_pending', 'error_description': 'Precondition Required', 'code': 428}
2024-05-16 18:17:27.099 T:3061067   error <general>: Skipped 1 duplicate messages..
2024-05-16 18:17:27.099 T:3061067   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: int() argument must be a string, a bytes-like object or a number, not 'tuple'
                                                   Traceback (most recent call last):
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 63, in run
                                                       plugin.run(provider, context)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 156, in run
                                                       result, options = provider.navigate(context)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 142, in navigate
                                                       result = method(context, re_match)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 345, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 755, in _on_sign
                                                       yt_login.process(mode, self, context)
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_login.py", line 181, in process
                                                       access_manager.update_access_token(
                                                     File "/home/serge/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/access_manager.py", line 429, in update_access_token
                                                       current_user['token_expires'] = int(unix_timestamp)
                                                   TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
                                                   -->End of Python script error report<--

2024-05-16 18:17:27.114 T:3051747    info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-16 18:17:27.197 T:3061093   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/sign/in/?category_label=Sign%20In
2024-05-16 18:17:27.212 T:3051715   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/sign/in/?category_label=Sign%20In) failed
2024-05-16 18:17:27.714 T:3061287    info <general>: [plugin.video.youtube] Running: YouTube (7.0.7+beta.1) on Nexus (Kodi-20.2) with Python 3.8.10
                                                   Path: /
                                                   Params: {}
2024-05-16 18:17:28.096 T:3051747    info <general>: PulseAudio: Opened device alsa_output.pci-0000_00_02.0.hdmi-stereo in pcm mode with Buffersize 200 ms Periodsize 50 ms
2024-05-16 18:35:32.608 T:3065091    info <general>: WEATHER: Downloading weather

```

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by MoojMidge** [comment] 2024-05-16 19:50
Duplicate of #759

**Closed as not planned by MoojMidge** 2024-05-16 19:50 UTC
Labels: bug
