### ISSUE TITLE
Video fails to load for about a minute before a new click works

### ISSUE THREAD

**Issue by mimre25** [anxdpanic/plugin.video.youtube#913] opened 2024-09-27 18:24 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.0+beta2 (this has already been happening before I upgraded to 7.1.0+beta2) 
* Kodi Version: 20.5 (Kodi Media Center 20.5 (20.5.0) Git:20240501-8c8d7afa26)
* Kodi GUI Language: English
* Operating System: Raspberry Pi OS 64 bit
* Operating System Language: English

------

### Expected Behavior
Videos load the first time.

------

### Current Behavior
When I select a video, it fails loading and I get an "erratic" loading spinner with the 
"accept" sound alternating.
After a while I get an error message saying the video failed loading and I can click "ok" and then select a video again. 
Then it succeeds.

Note: This does not happen for the first video I'm playing in a session. 

------

### Steps to Reproduce
1. Finish a video
2. Select the next one
3. - that's it

------

### Log

```console
# previous video
2024-09-27 18:45:15.712 T:132346    info <general>: ProcessDecoderOutput: Changed max allowed Out-Of-Sync value to 94 ms due self-learning
# previous video finished
# selecting next video
2024-09-27 18:52:17.120 T:132346    info <general>: CVideoPlayerAudio::Process - stream stalled
2024-09-27 18:52:17.162 T:132339    info <general>: Process - eof reading from demuxer
2024-09-27 18:52:17.162 T:132339    info <general>: CVideoPlayer::OnExit()
2024-09-27 18:52:17.162 T:132339    info <general>: VideoPlayer: eof, waiting for queues to empty
2024-09-27 18:52:17.162 T:132339    info <general>: Closing stream player 1
2024-09-27 18:52:17.164 T:132339    info <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
2024-09-27 18:52:17.164 T:132339    info <general>: Waiting for audio thread to exit
2024-09-27 18:52:17.164 T:132346    info <general>: thread end: CVideoPlayerAudio::OnExit()
2024-09-27 18:52:17.165 T:132339    info <general>: Closing audio device
2024-09-27 18:52:17.170 T:132339    info <general>: Deleting audio codec
2024-09-27 18:52:17.170 T:132339    info <general>: Closing stream player 2
2024-09-27 18:52:17.173 T:132339    info <general>: CDVDMessageQueue(video)::WaitUntilEmpty
2024-09-27 18:52:17.338 T:132339    info <general>: waiting for video thread to exit
2024-09-27 18:52:17.338 T:132344    info <general>: thread end: video_thread
2024-09-27 18:52:17.339 T:132339    info <general>: deleting video codec
2024-09-27 18:52:17.372 T:132339    info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-09-27 18:52:17.415 T:2117     info <general>: CVideoPlayer::CloseFile()
2024-09-27 18:52:17.416 T:2117     info <general>: VideoPlayer: waiting for threads to exit
2024-09-27 18:52:17.416 T:2117     info <general>: VideoPlayer: finished waiting
2024-09-27 18:52:17.416 T:2117     info <general>: CVideoPlayer::CloseFile()
2024-09-27 18:52:17.416 T:2117     info <general>: VideoPlayer: waiting for threads to exit
2024-09-27 18:52:17.416 T:2117     info <general>: VideoPlayer: finished waiting
2024-09-27 18:52:17.455 T:2117     info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2024-09-27 18:52:17.596 T:2150     info <general>: CActiveAESink::OpenSink - initialize sink
2024-09-27 18:52:17.597 T:168381   error <general>: GetDirectory - Error getting -
2024-09-27 18:52:17.611 T:132331    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /channel/mine/playlist/PLfKXj9H8NPgkV41OWF5TmLf4mAYDKYAil/
                                                   Params: {'category_label': 'Watch Later'}
2024-09-27 18:52:17.908 T:2150    error <general>: PulseAudio: Sink ALSA:@ not found
2024-09-27 18:52:17.958 T:2150     info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2024-09-27 18:52:19.482 T:2117    error <general>: Control 525 in window 10025 has been asked to focus, but it can't
2024-09-27 18:52:19.509 T:132331    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /channel/mine/playlist/PLfKXj9H8NPgkV41OWF5TmLf4mAYDKYAil/
                                                   Params: {'category_label': 'Watch Later', 'refresh': 1}
2024-09-27 18:52:39.520 T:132331    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:39.949 T:132331   error <general>: [plugin.video.youtube] Player request failed
                                                   exc: |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))|
                                                   video_id: I-Sb6OAWm0k, client: ios, auth: True
                                                   Stack trace (most recent call last):
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 62, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 173, in run
                                                       result, options = provider.navigate(context)
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 164, in navigate
                                                       result = handler(provider=self, context=context, re_match=re_match)
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 362, in process
                                                       media_item = _play_stream(provider, context)
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 72, in _play_stream
                                                       streams = client.get_streams(context,
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 200, in get_streams
                                                       use_mpd=use_mpd).load_stream_info(video_id)
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/stream_info.py", line 1398, in load_stream_info
                                                       _result = self.request(
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/network/requests.py", line 126, in request
                                                       stack_trace = format_stack()
                                                   
2024-09-27 18:52:39.958 T:132331   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/plugin.py", line 16, in <module>
                                                       plugin_runner.run()
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin_runner.py", line 62, in run
                                                       plugin.run(provider, context, focused=(current_uri == new_uri))
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/plugin/xbmc/xbmc_plugin.py", line 173, in run
                                                       result, options = provider.navigate(context)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 164, in navigate
                                                       result = handler(provider=self, context=context, re_match=re_match)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 362, in process
                                                       media_item = _play_stream(provider, context)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 72, in _play_stream
                                                       streams = client.get_streams(context,
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 200, in get_streams
                                                       use_mpd=use_mpd).load_stream_info(video_id)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/martin/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/stream_info.py", line 1412, in load_stream_info
                                                       video_details = _result.get('videoDetails', {})
                                                                       ^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2024-09-27 18:52:40.149 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:47.147 T:168423    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:47.166 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:47.185 T:168423 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:47.186 T:168423 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:47.831 T:168426    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:47.849 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:48.001 T:168426 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:48.002 T:168426 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:48.664 T:168428    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:48.682 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:48.825 T:168428 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:48.825 T:168428 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:49.481 T:168430    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:49.499 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:49.652 T:168430 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:49.653 T:168430 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:50.331 T:168432    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:50.349 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:50.486 T:168432 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:50.486 T:168432 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:51.147 T:168434    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:51.165 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:51.318 T:168434 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:51.318 T:168434 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:52.031 T:168436    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:52.049 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:52.196 T:168436 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:52.196 T:168436 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:52.866 T:168438    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:52.882 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:53.036 T:168438 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:53.036 T:168438 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:53.714 T:168440    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:53.732 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:53.868 T:168440 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:53.868 T:168440 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:54.514 T:168442    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:54.532 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:54.693 T:168442 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:54.693 T:168442 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:55.364 T:168444    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:55.382 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:55.517 T:168444 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:55.517 T:168444 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:56.164 T:168446    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:56.182 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:56.335 T:168446 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:56.335 T:168446 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:57.014 T:168448    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:57.032 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:57.167 T:168448 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:57.167 T:168448 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:57.814 T:168450    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:57.832 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:57.986 T:168450 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:57.986 T:168450 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:58.664 T:168452    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:58.682 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:58.819 T:168452 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:58.819 T:168452 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:52:59.481 T:168454    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:52:59.499 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:52:59.654 T:168454 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:52:59.654 T:168454 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:53:00.347 T:168456    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:53:00.365 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:53:00.371 T:168456 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:53:00.371 T:168456 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:53:00.997 T:168458    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:53:01.014 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:53:01.015 T:168458 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - plugin call stopped to avoid Kodi crash
2024-09-27 18:53:08.635 T:168458    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:53:08.636 T:2117    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k]
2024-09-27 18:53:08.668 T:168458 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:53:08.669 T:168458 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:53:09.347 T:168463    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'I-Sb6OAWm0k'}
2024-09-27 18:53:10.259 T:2117     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=I-Sb6OAWm0k
2024-09-27 18:53:10.262 T:168465    info <general>: Creating InputStream
2024-09-27 18:53:10.263 T:168465   error <general>: AddOnLog: inputstream.adaptive: Resolution not valid on "inputstream.adaptive.chooser_resolution_max" property.
2024-09-27 18:53:10.265 T:168465    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-09-27 18:53:10.389 T:168465    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 2, Type: VOD)
2024-09-27 18:53:10.390 T:168465    info <general>: Creating Demuxer
2024-09-27 18:53:10.390 T:168465    info <general>: Opening stream: 1001 source: 256
2024-09-27 18:53:10.648 T:168465    info <general>: Creating video codec with codec id: 167
2024-09-27 18:53:10.649 T:168465    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder V4L2 mem2mem VP9 decoder wrapper
2024-09-27 18:53:10.649 T:168465    info <general>: CDVDVideoCodecDRMPRIME::Open - unable to open codec
2024-09-27 18:53:10.650 T:168465    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder Google VP9
2024-09-27 18:53:10.658 T:168465    info <general>: Creating video thread
2024-09-27 18:53:10.658 T:168473    info <general>: running thread: video_thread
2024-09-27 18:53:10.658 T:168465    info <general>: Opening stream: 1002 source: 256
2024-09-27 18:53:10.724 T:168465    info <general>: Finding audio codec for: 86018
2024-09-27 18:53:10.733 T:168465    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-09-27 18:53:10.733 T:168465    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-09-27 18:53:10.733 T:168465    info <general>: Creating audio thread
2024-09-27 18:53:10.733 T:168475    info <general>: running thread: CVideoPlayerAudio::Process()
2024-09-27 18:53:10.926 T:168475    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-09-27 18:53:10.926 T:168475    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2024-09-27 18:53:10.930 T:2150     info <general>: CActiveAESink::OpenSink - initialize sink
2024-09-27 18:53:11.073 T:168473   error <general>: CDVDVideoCodecDRMPRIME::FilterOpen - avfilter_graph_config:  Function not implemented (-38)
2024-09-27 18:53:11.250 T:2150    error <general>: PulseAudio: Sink ALSA:@ not found
2024-09-27 18:53:11.305 T:2150     info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2024-09-27 18:53:11.343 T:2117    error <general>: Window Translator: Can't find window True
2024-09-27 18:53:22.584 T:2117    error <general>: Control 51 in window 10025 has been asked to focus, but it can't
2024-09-27 18:53:22.676 T:168463    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /channel/mine/playlist/PLfKXj9H8NPgkV41OWF5TmLf4mAYDKYAil/
                                                   Params: {'category_label': 'Watch Later', 'refresh': 1}
2024-09-27 18:53:22.676 T:169798   error <general>: GetDirectory - Error getting plugin://plugin.video.youtube/channel/mine/playlist/PLfKXj9H8NPgkV41OWF5TmLf4mAYDKYAil/?category_label=Watch+Later&refresh=1
2024-09-27 18:53:22.677 T:2117    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/channel/mine/playlist/PLfKXj9H8NPgkV41OWF5TmLf4mAYDKYAil/?category_label=Watch+Later&refresh=1) failed
2024-09-27 18:53:22.702 T:168463 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - playlist cleared to avoid Kodi crash
2024-09-27 18:53:22.702 T:168463 warning <general>: [plugin.video.youtube] Multiple busy dialogs active - reloading playlist
2024-09-27 18:53:40.925 T:168475    info <general>: ProcessDecoderOutput: Changed max allowed Out-Of-Sync value to 100 ms due self-learning
2024-09-27 18:54:00.585 T:2117     info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2024-09-27 18:54:00.713 T:172194   error <general>: GetDirectory - Error getting -
2024-09-27 18:54:02.547 T:172468    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /channel/mine/playlist/PLfKXj9H8NPgkV41OWF5TmLf4mAYDKYAil/
                                                   Params: {'category_label': 'Watch Later'}
2024-09-27 18:54:21.419 T:172468    info <general>: [plugin.video.youtube] Running: YouTube (7.1.0+beta.2) on Nexus (Kodi-20.5) with Python 3.11.2
                                                   Path: /play/
                                                   Params: {'video_id': 'xV4rLfpidIk'}
2024-09-27 18:54:22.385 T:2117     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=xV4rLfpidIk
2024-09-27 18:54:22.403 T:168473 warning <general>: OutputPicture - timeout waiting for buffer
2024-09-27 18:54:22.569 T:168465    info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-09-27 18:54:22.569 T:168465    info <general>: Creating InputStream
2024-09-27 18:54:22.571 T:168465   error <general>: AddOnLog: inputstream.adaptive: Resolution not valid on "inputstream.adaptive.chooser_resolution_max" property.
2024-09-27 18:54:22.572 T:168465    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-09-27 18:54:22.576 T:168465    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 2, Type: VOD)
2024-09-27 18:54:22.576 T:168465    info <general>: Creating Demuxer
2024-09-27 18:54:22.576 T:168465    info <general>: Opening stream: 1001 source: 256
2024-09-27 18:54:22.802 T:168465    info <general>: Creating video codec with codec id: 167
2024-09-27 18:54:22.802 T:168465    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder V4L2 mem2mem VP9 decoder wrapper
2024-09-27 18:54:22.803 T:168465    info <general>: CDVDVideoCodecDRMPRIME::Open - unable to open codec
2024-09-27 18:54:22.803 T:168465    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder Google VP9
2024-09-27 18:54:22.804 T:168465    info <general>: Opening stream: 1002 source: 256
2024-09-27 18:54:22.868 T:168465    info <general>: Finding audio codec for: 86076
2024-09-27 18:54:22.869 T:168465    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder opus
2024-09-27 18:54:22.871 T:168475    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 100 ms
2024-09-27 18:54:23.226 T:168475    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder opus
2024-09-27 18:54:23.228 T:168475    info <general>: Creating audio stream (codec id: 86076, channels: 2, sample rate: 48000, no pass-through)
2024-09-27 18:54:23.253 T:2150     info <general>: CActiveAESink::OpenSink - initialize sink
2024-09-27 18:54:23.273 T:168473   error <general>: CDVDVideoCodecDRMPRIME::FilterOpen - avfilter_graph_config:  Function not implemented (-38)
2024-09-27 18:54:23.563 T:2150    error <general>: PulseAudio: Sink ALSA:@ not found
2024-09-27 18:54:23.617 T:2150     info <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2024-09-27 18:54:23.640 T:2117    error <general>: Window Translator: Can't find window True
# video plays
```

**Comment by MoojMidge** [comment] 2024-09-27 22:19
> * Add-on Version: 7.1.0+beta2 (this has already been happening before I upgraded to 7.1.0+beta2)

When did you first start seeing this occur? Root cause is this:

> ```
> ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> ```

Can better handle the error, and depending on when you first started experiencing the problem, possibly workaround it as well, but there may be an underlying issue with your network closing connections.

**Comment by MoojMidge** [comment] 2024-09-28 00:39
See if https://github.com/MoojMidge/plugin.video.youtube/archive/refs/heads/master.zip improves things

**Comment by mimre25** [comment] 2024-09-28 05:48
> When did you first start seeing this occur?

About a month ago. At that time nothing had changed in my setup. 
After this bugging me for a few weeks I decided to upgrade to the beta in hope of a fix.

Anyhow, I'll try the latest zip later today

**Comment by MoojMidge** [comment] 2024-09-28 06:34
> About a month ago. At that time nothing had changed in my setup.

That is around the time I removed the retry attempts for certain types of requests made to the YouTube servers, because of unintended consequences that may result.

The zip file adds the retry attempts back in, but as mentioned before there is something wrong with your system/network closing connections that should be kept alive.

**Comment by mimre25** [comment] 2024-09-28 07:36
> The zip file adds the retry attempts back in, but as mentioned before there is something wrong with your system/network closing connections that should be kept alive.

My initial tests can confirm that this helps - I'll report back after a few days on whether the issue re-appeared or not.

In the meantime I'm gonna look into the networking side of things - thanks for pointing that out!

Also thanks for the super quick fix!

**Closed as completed** 2024-10-02 20:47 UTC
Labels: bug

**Comment by mimre25** [comment] 2024-10-03 15:41
To report back as promised: The issues are gone.

Also, I have figured out one potential source of the disconnects, so I'll document this here in case someone gets here via googling :slightly_smiling_face: :

Raspberry PI OS has WiFi power saving on per default. It can be disabled with
```sh
nmcli con mod preconfigured wifi.powersave disable
```

**Comment by MoojMidge** [comment] 2024-10-03 20:55
Thanks for providing that info.

I'll leave the retry for POST requests enabled unless there are actual issues reported with it. If I need to consider disabling it again I'll update this issue.
