### ISSUE TITLE
Login Failed: Unknown response

### ISSUE THREAD

**Issue by mejico** [anxdpanic/plugin.video.youtube#1006] opened 2024-12-02 05:09 UTC
The problem started just over a week ago when I was unable to playback any videos.  So, I upgraded to v 7.1.1.3 but still had the problem.  So, I create new API key and OAuth clients, and I still can't playback any video, I also notice when I login it only prompts me to go through the process once, where in the past it would prompt twice.

Please provide any relevant information about your setup

* Add-on Version:  7.1.1.3
* Kodi Version:       21.1
* Kodi GUI Language:  English
* Operating System:  Windows 11
* Operating System Language:  English

------

### Expected Behavior

Play any video

------

### Current Behavior

Can't play any videos

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Upgrade plugin via Zip
2. Run setup wizard
3.  Sign in

Log File

[kodi.old.log](https://github.com/user-attachments/files/17972810/kodi.old.log)

**Comment by MoojMidge** [comment] 2024-12-02 07:19
Login appears to be working fine, but you appear to be trying to access your local network through a Cloudfare proxy or tunnel which obviously fails because there are no authorisation headers to allow access.

Run the Setup Wizard and apply the recommended settings. If it still doesn't work then get a debug log or enable debug logging in this addon `Settings > Advanced > Logging > Enable debug logging`

**Comment by mejico** [comment] 2024-12-02 09:16
will do

**Comment by mejico** [comment] 2024-12-02 09:25
[kodi.log](https://github.com/user-attachments/files/17975638/kodi.log)


Ran setup wizard here's the log.

**Comment by MoojMidge** [comment] 2024-12-02 09:45
```
2024-12-02 20:18:32.587 T:6216    debug <general>: [plugin.video.youtube] HTTPServer - GET
                                                   	Path:        |/youtube/manifest/dash?file=8d5WIrFg260.mpd|
                                                   	Address:     |1.1.1.175|
                                                   	Whitelisted: False
                                                   	Local range: False
                                                   	Status:      Blocked
```

Don't really know what is going on with your network but the local http server is listening and receiving requests from a public Cloudfare IP address.

Whatever is is happening is also resulting in a bunch of other network issues on your system, but I am going to assume you have done this deliberately because you are accessing SMB shares on `1.1.1.160`.

I can't really provide support for this aside from informing you that it is possible to whitelist access to the http server via `1.1.1.175` using the following setting:
`YouTube > Settings > Advanced > HTTP Server > Whitelist` and typing in `1.1.1.175`.

However I must also recommend that you do not do this, as without understanding why or how you have set up your network, whitelisting this IP seems like a bad idea.

**Comment by mejico** [comment] 2024-12-02 10:51
I don't know if this helps, but 1.1.1.1 refers to my gateway (router) and not cloudflare

**Comment by mejico** [comment] 2024-12-02 10:54
I will muck around with the dins in the morning, but the funny thing is,  I have been using the 1.1.1.xxx network for almost 3 decades and never had issues.  Also the actual DNS my router points to is one of the adblocking DNS servers.

**Comment by MoojMidge** [comment] 2024-12-02 14:00
> I don't know if this helps, but 1.1.1.1 refers to my gateway (router) and not cloudflare

The problem is that this is a public IP address, that happens to belong to Cloudflare. I'm guessing that if you type in `1.1.1.1` in a web browser it open your router admin page or similar? It should actually open [this](https://one.one.one.one/).

As I mentioned i don't feel comfortable offering any suggesting for what you should do in this situation, given how untoward this seems, even if you have been doing this for 30 years without issue and therefore presumably have your firewalls, DNS servers, routing etc all setup to support this

The only thing I will suggest is that you may be able to side step the problem with this addon in particular by selecting `127.0.0.1` as the listen address for the http server, rather than `0.0.0.0` in `Settings > Advanced > HTTP Server > Select listen IP`

**Comment by mejico** [comment] 2024-12-02 22:07
Will try that

**Comment by mejico** [comment] 2024-12-02 22:17
Setting the listen to loopback worked.  Thanks for the help.  You have also helped me in the past, but you closed the issue before I got to thank you.  Once again, many thanks.

**Comment by mejico** [comment] 2024-12-02 22:22
As a footnote I don't believe this was the original problem that stopped video playback, as it coincided with an issue many other people also had.  In trying to fix the original problem, I may have inadvertently caused a new problem, I also noticed that the original problem coincided with that current changes Google are making to the OAuth system.  Getting back to one of your earlier suggestions I could have changed the DNS on that machine to 0.0.0.0

**Comment by MoojMidge** [comment] 2024-12-03 03:19
> You have also helped me in the past, but you closed the issue before I got to thank you. Once again, many thanks.

No problems. Note that closing an issue doesn't mean that you can't still discuss things about it, it is just a means of keeping track of pending actions. An issue can always be reopened as well if needed. 



> As a footnote ...

Difficult to say what came first, but i suspect with the listen address and your specific network setup MPEG-DASH playback would not have worked previously. The streams that could be played without using MPEG-DASH were progressively removed culminating in the OAuth changes that also further restricted the available streams.

**Closed as completed** 2024-12-04 21:01 UTC
Labels: bug
