### ISSUE TITLE
Youtube 7.02 branch breaks subtitles loading

### ISSUE THREAD

**Issue by karlo2105** [anxdpanic/plugin.video.youtube#534] opened 2023-11-12 21:31 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.02.2
* Kodi Version: 20.2
* Kodi GUI Language: French
* Operating System: Android 10
* Operating System Language: French

------

### Expected Behavior

Loading subtitles with video should launch it but it's not case with 7.02 branch. 

------

### Current Behavior

Since 7.02 branch push, subtitles loading has been broken. I had to revert back to 7.01 branch and to block auto update in order to fix. 

------

### Steps to Reproduce

1. Open Youtube 7.02.2
2. Hit middle button in order to select subtitles
3. Choose subs
4. Video shall not start

------

### Additional Information

I am not the only one stuck with this bug : 
https://forum.kodi.tv/showthread.php?tid=356934&pid=3171780#pid3171780

------

**Comment by MoojMidge** [comment] 2023-11-15 00:50
The subtitle language selection dialog currently doesn't work.

If you predominately use English subtitles, then go to `Settings > General > Configure subtitles` and choose an option instead of `Prompt` as a workaround.

Alternatively, if you are able to do so, the changes required to fix this can be seen here: https://github.com/MoojMidge/plugin.video.youtube/commit/b9296e699ad0cf21c2e69d2afdf777e11b273e8a. You can fix this yourself until the next release is available.

**Comment by MoojMidge** [comment] 2023-11-15 00:50
Duplicate of #525

**Comment by MoojMidge** [comment] 2023-11-15 01:18
Re-opening this issue, as it contains more specific details and description of the issue.

**Comment by trunksjiang78** [comment] 2023-11-26 02:57
I have the same problem...

**Closed as completed** 2023-12-26 00:56 UTC
Labels: bug
