### ISSUE TITLE
Live streams issues

### ISSUE THREAD

**Issue by kimadea** [anxdpanic/plugin.video.youtube#1004] opened 2024-11-28 16:14 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 7.1.1.1
* Kodi Version: v21.1 (Kodi Omega)
* Kodi GUI Language: Spanish
* Operating System: Windows Pro 10
* Operating System Language: Spanish

------

Actually I have two issues:
a) with the new version of the addon, the path for channel live streams on IPTV Simple Client doesn't work
    example path:
    plugin://plugin.video.youtube/play/?channel_id=UCj6PcyLvpnIRT_2W_mwa9Aw&live=1

    On older versions of the addon, on provider.py file you can find this on #686 line
    """
    Plays a video.
    path for video: '/play/?video_id=XXXXXXX'

    path for playlist: '/play/?playlist_id=XXXXXXX&mode=[OPTION]'
    OPTION: [normal(default)|reverse|shuffle]
    
    path for channel live streams: '/play/?channel_id=UCXXXXXXX&live=X
    OPTION: 
        live parameter required, live=1 for first live stream
        live = index of live stream if channel has multiple live streams
    """
    [reference: https://github.com/anxdpanic/plugin.video.youtube/issues/432]
    
    Log a) issue https://pastecode.io/s/k8en8y0w  

b) although the live streams with the url video_id are playable, they are not working correctly: usually there is a huge time offset backwards and the log file shows some warnings and errors 
   Here is the log file:
   Log b) issue https://pastecode.io/s/7rp47ufu 

Thank you very much for all you do with this great addon.

**Comment by MoojMidge** [comment] 2024-11-28 16:38
Can you try v7.1.1.3?
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.1.1.3

I don't think it will necessarily do anything for issue b) but issue a) should be fixed.

**Comment by kimadea** [comment] 2024-11-28 18:43
Thanks a lot!! Issue a) was solved.  
As for b) issue, right now some of the live streams do not have audio. 

channel LN+
plugin://plugin.video.youtube/play/?channel_id=UCba3hpU7EFBSk817y9qZkiA&live=1
plugin://plugin.video.youtube/play/?video_id=G5pHuBCqgrs

channel C5N
plugin://plugin.video.youtube/play/?channel_id=UCFgk2Q2mVO1BklRQhSv6p0w&live=1
plugin://plugin.video.youtube/play/?video_id=N1Tfrn7hMWU

channel 26
plugin://plugin.video.youtube/play/?video_id=9fkB8aDdSik

Log no audio
https://pastecode.io/s/v9k8gkhw

**Comment by MoojMidge** [comment] 2024-11-28 21:01
Seems to be a regression in InputStream.Adaptive with handling the HLS streams.

For the moment you can try selecting `YouTube > Settings > Advanced > InputStream.Adaptive > Use for live streams > MPEG-DASH`

**Comment by kimadea** [comment] 2024-11-28 22:16
With the change in the settings the audio works.
Thank you very much once again.

**Closed as completed** 2024-11-28 22:44 UTC
Labels: bug
